---

- name: Lutim | Install service
  template:
    src: etc/systemd/system/lutim.service.j2
    dest: "/etc/systemd/system/lutim.service"
    owner: root
    group: root
    mode: 0644
  notify: reload systemd daemons
