---

- name: Lutim | Copy upstart service config
  template:
    src: etc/default/lutim.j2
    dest: "/etc/default/lutim"
    owner: root
    group: root
    mode: 0644
  notify: restart lutim

- name: Lutim | Copy upstart config
  command: creates=/etc/init/lutim.conf cp {{ lutim_site.working_dir }}/utilities/lutim_upstart.conf /etc/init/lutim.conf
