---

- name: Lutim | Create working directory
  file:
    dest: "{{ lutim_working_dir }}"
    state: directory

- name: Lutim | Checkout git repository
  git:
    repo: https://framagit.org/noplanman/lutim.git
    dest: "{{ lutim_working_dir }}"
    update: "{{ lutim_keep_updated }}"
  register: lutim_git_updated
  notify: restart lutim

- name: Lutim | Copy config
  template:
    src: lutim.conf.j2
    dest: "{{ lutim_working_dir }}/lutim.conf"
    mode: 0644
  notify: restart lutim

- name: Lutim | Install lutim
  command: carton install
  args:
    chdir: "{{ lutim_working_dir }}"
  when: lutim_git_updated.changed
  notify: restart lutim

- name: Lutim | Set permissions on working directory
  file:
    path: "{{ lutim_working_dir }}"
    state: directory
    owner: "{{ lutim_user }}"
    group: "{{ lutim_group }}"
    recurse: yes
