---

- name: Lutim | Create working directory
  file:
    dest: "{{ lutim_working_dir }}"
    state: directory

- name: Lutim | Checkout git repository
  git:
    repo: https://framagit.org/noplanman/lutim.git
    dest: "{{ lutim_working_dir }}"
    update: "{{ lutim_keep_updated }}"
  register: lutim_git_updated
  notify: restart lutim

- name: Lutim | Copy config
  template:
    src: lutim.conf.j2
    dest: "{{ lutim_working_dir }}/lutim.conf"
    mode: 0644
  notify: restart lutim

- name: Lutim | Install lutim
  command: carton install
  args:
    chdir: "{{ lutim_working_dir }}"
    creates: "{{ lutim_db_path }}"
  when: lutim_git_updated.changed
  register: lutim_app_installed
  notify: restart lutim

- name: Lutim | Update lutim
  command: carton update
  args:
    chdir: "{{ lutim_working_dir }}"
  when: not lutim_app_installed.changed and lutim_keep_updated
  register: lutim_app_updated
  changed_when: "'Successfully installed' in lutim_app_updated.stdout"
  notify: restart lutim

- name: Lutim | Set permissions on working directory
  file:
    path: "{{ lutim_working_dir }}"
    state: directory
    owner: "{{ lutim_user }}"
    group: "{{ lutim_group }}"
    recurse: yes
