---

- name: Lutim | Checkout git repository
  git:
    repo: https://framagit.org/noplanman/lutim.git
    dest: "{{ lutim_working_dir }}"
    update: "{{ lutim_keep_updated }}"
    force: yes
  register: lutim_git_updated
  changed_when: lutim_git_updated.after != lutim_git_updated.before
  notify: restart lutim

- name: Lutim | Copy config
  template:
    src: lutim.conf.j2
    dest: "{{ lutim_working_dir }}/lutim.conf"
    mode: 0644
  notify: restart lutim

- name: Lutim | Install lutim
  command: carton install
  args:
    chdir: "{{ lutim_working_dir }}"
    creates: "{{ lutim_db_path }}"
  register: lutim_app_installed
  notify: restart lutim

- name: Lutim | Update lutim
  command: carton update
  args:
    chdir: "{{ lutim_working_dir }}"
  when: lutim_app_installed.changed or lutim_keep_updated
  register: lutim_app_updated
  changed_when: "'Successfully installed' in lutim_app_updated.stdout"
  notify: restart lutim

- name: Lutim | Set ownership on working directory
  file:
    path: "{{ lutim_working_dir }}"
    state: directory
    owner: "{{ lutim_user }}"
    group: "{{ lutim_group }}"
    recurse: yes
  register: lutim_ownership_set
  changed_when: lutim_ownership_set.diff.after|to_json != lutim_ownership_set.diff.before|to_json
